### ISSUE TITLE
New Spinner

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#167]
New Spinner that is pet related 

Examples

- Spinning Paw logo
- Growing Paw logo
- Feel Free to suggest new ideas or creative

## TASKS

- [ ] Create New Spinner
- [ ] Put New spinner in `/shared/Spinner`
- [ ] Edit the index.js in `/shared/Spinner` to use the new Spinner
